"""test modules

Revision ID: 26cab4ad4380
Revises: fd8ecd2cdcc5
Create Date: 2025-12-22 14:52:09.403086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26cab4ad4380'
down_revision: Union[str, None] = 'fd8ecd2cdcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    #op.drop_table('feedback')
    #op.drop_index(op.f('ix_theories_id'), table_name='theories')
    #op.drop_table('theories')
    #op.drop_index(op.f('ix_courses_id'), table_name='courses')
    #op.drop_index(op.f('ix_courses_owner_id'), table_name='courses')
    #op.drop_table('courses')
    #op.drop_index(op.f('ix_module_versions_id'), table_name='module_versions')
    #op.drop_table('module_versions')
    #op.drop_index(op.f('ix_course_versions_id'), table_name='course_versions')
    #op.drop_table('course_versions')
    #op.drop_index(op.f('ix_users_email'), table_name='users')
    #op.drop_index(op.f('ix_users_id'), table_name='users')
    #op.drop_table('users')
    #op.drop_index(op.f('ix_course_structure_id'), table_name='course_structure')
    #op.drop_table('course_structure')
    #op.drop_index(op.f('ix_modules_id'), table_name='modules')
    #op.drop_table('modules')
    #op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    #op.drop_table('lessons')
    #op.drop_index(op.f('ix_tests_id'), table_name='tests')
    #op.drop_table('tests')
    #op.drop_index(op.f('ix_lesson_versions_id'), table_name='lesson_versions')
    #op.drop_table('lesson_versions')
    #op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    #op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('tasks_module_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('lesson_versions',
    sa.Column('module_version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_version_id'], ['module_versions.id'], name=op.f('lesson_versions_module_version_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_versions_pkey'))
    )
    op.create_index(op.f('ix_lesson_versions_id'), 'lesson_versions', ['id'], unique=False)
    op.create_table('tests',
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('tests_module_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tests_pkey'))
    )
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('lessons_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name='lessons_module_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lessons_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('modules',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('modules_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='modules_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='modules_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('course_structure',
    sa.Column('sections', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tests_per_section', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lessons_per_section', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions_per_test', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('final_test', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('content_types', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('course_structure_pkey'))
    )
    op.create_index(op.f('ix_course_structure_id'), 'course_structure', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('course_versions',
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('course_versions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_versions_course_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='course_versions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_course_versions_id'), 'course_versions', ['id'], unique=False)
    op.create_table('module_versions',
    sa.Column('course_version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], name=op.f('module_versions_course_version_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('module_versions_pkey'))
    )
    op.create_index(op.f('ix_module_versions_id'), 'module_versions', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('courses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['course_versions.id'], name='courses_current_version_id_fkey'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='courses_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='courses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_courses_owner_id'), 'courses', ['owner_id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('theories',
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('theories_lesson_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('theories_pkey'))
    )
    op.create_index(op.f('ix_theories_id'), 'theories', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('feedback_author_id_fkey')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('feedback_lesson_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    # ### end Alembic commands ###
