"""Add current_version_id to course

Revision ID: 60e5aebc1190
Revises: 3cdc28e805a5
Create Date: 2025-04-11 11:51:31.228863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e5aebc1190'
down_revision: Union[str, None] = '3cdc28e805a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_theories_id', table_name='theories')
    op.drop_table('theories')
    op.add_column('courses', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'course_versions', ['current_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'current_version_id')
    op.create_table('theories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='theories_lesson_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='theories_pkey')
    )
    op.create_index('ix_theories_id', 'theories', ['id'], unique=False)
    # ### end Alembic commands ###
