"""Add base mixin fields

Revision ID: fd8ecd2cdcc5
Revises: 1b4264d70bcb
Create Date: 2025-11-21 00:54:08.764226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd8ecd2cdcc5'
down_revision: Union[str, None] = '1b4264d70bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_course_structure_id'), table_name='course_structure')
    op.drop_table('course_structure')
    op.drop_constraint('courses_current_version_id_fkey', 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_course_versions_id'), table_name='course_versions')
    op.drop_table('course_versions')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('courses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['course_versions.id'], name='courses_current_version_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='courses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('course_structure',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sections', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tests_per_section', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lessons_per_section', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions_per_test', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('final_test', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('content_types', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('course_structure_pkey'))
    )
    op.create_index(op.f('ix_course_structure_id'), 'course_structure', ['id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('modules_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='modules_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='modules_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('tasks_module_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('tests_module_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tests_pkey'))
    )
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_table('course_versions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('course_versions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_versions_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='course_versions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_course_versions_id'), 'course_versions', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('lessons_module_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey'))
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    # ### end Alembic commands ###
