name: CI

on:
  push:
    branches: [ main ]      # или [ dev, main ], если у вас есть ветка dev
  pull_request:
    branches: [ main ]

jobs:
  call-org-ci:
    # здесь вызываем ваш шаблон
    uses: NeuroFlexDev/org-configs/.github/workflows/ci.yml@main
    with:
      ref: ${{ github.ref_name }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
